### ISSUE TITLE
Rudder Firebase and Facebook dependent on different versions of Rudder

### ISSUE THREAD

**Issue by hamed-ice** [rudderlabs/rudder-integration-firebase-swift#7]
Can I have both Rudder Facebook and Firebase at the same time?
Facebook depends on Rudder version 1 and Firebase on version 2, I  installed both together. but Rudder Facebook has an error with Rudder 2.2.7

Error: 'Rudder/Rudder.h' file not found

**Comment by pallabmaiti** [comment]
For Rudder v1:
https://github.com/rudderlabs/rudder-integration-facebook-ios
https://github.com/rudderlabs/rudder-integration-firebase-ios

For Rudder v2:
https://github.com/rudderlabs/rudder-integration-facebook-app-events-swift
https://github.com/rudderlabs/rudder-integration-firebase-swift
