### ISSUE TITLE
Track method not called in RudderFirebaseDestination

### ISSUE THREAD

**Issue by hamedaakhlaghi** [rudderlabs/rudder-integration-firebase-swift#8]
I have added Firebase as a destination in my project, but it seems that the track method in RudderFirebaseDestination is not being called. As a result, I am unable to see any events in Firebase.

I have already tested the Firebase implementation separately, and everything appears to be functioning correctly. I can see crashes and debug events in Firebase's debugView. However, when I track events using Rudder, they do not appear in the Firebase panel.

note: I can see the events in facebook manager.

Here is the code snippet I used to add the Firebase destination after confining rudder:
```
RSClient.sharedInstance().addDestination(RudderFirebaseDestination())
````
I have followed the documentation provided and ensured that I have implemented the necessary steps correctly.

Any assistance in resolving this issue would be greatly appreciated. Thank you.

**Comment by 1abhishekpandey** [comment]
Hey @hamedaakhlaghi,
I just verified that the RudderFirebase destination is working as expected and track events are working correctly.
I would like you to please perform a couple of debugging steps to ensure RudderFirebase is setup properly:

1. Could you please add a debug breakpoint at [this](https://github.com/rudderlabs/rudder-integration-firebase-swift/blob/70a3c3b8b1ca2ff3f5a25e28d1c5d9007dffc460/Sources/Classes/RSFirebaseDestination.swift#L96) location and check if the control reaches there when you make a track event, for example: `RSClient.sharedInstance().track("single_track_call")).`
2. Could you please enable debug mode in the app by referring to [this](https://firebase.google.com/docs/app-check/ios/debug-provider) Firebase documentation, and check if you can see the corresponding logs in Xcode when you make any track or screen events?
3. Could you please set up a new sample iOS app and configure the RudderFirebase destination in that app and check if track events are made over there or not?

**Comment by 1abhishekpandey** [comment]
We are closing this issue as there have been no updates. If the issue continues to persist, please reopen it or revert back with details.
